class SupabaseConfig {
  static const String url = 'https://ogrebetlhwzfywuvgijl.supabase.co';
  static const String anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ncmViZXRsaHd6Znl3dXZnaWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODQ0MTYsImV4cCI6MjA3Mzg2MDQxNn0.7ALejILrqoUH1CWbVN8GGBM2nE8PSsmdgBKEefdnYvw';
  static const String serviceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ncmViZXRsaHd6Znl3dXZnaWpsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODI4NDQxNiwiZXhwIjoyMDczODYwNDE2fQ.cQpCyx1skgzjRygANzutYLQwX2l14yErdcV0DuCLy40';
}

